# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-20 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170822_1647'),
        ('user', '0003_auto_20170818_1344'),
    ]

    operations = [
    ]
